version: '2'
services:
    postgres:
        image: postgres:9.6.1
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=myapp
            - POSTGRES_PASSWORD=my-password
    wildfly:
        image: tonda100/wildfly-postgresql
        ports:
            - "8080:8080"
        environment:
            - DB_HOST=postgres
            - DB_NAME=myapp
            - DB_USER=myapp
            - DB_PASS=my-password
        depends_on:
            - postgres